# Generated by Django 3.2.22 on 2023-12-01 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0006_alter_sitesettings_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='ship_fee_cold_chain',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='ship_fee_regular',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
    ]
