# Generated by Django 3.2.25 on 2024-05-02 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0008_auto_20240502_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='domain_name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
