# Generated by Django 3.2.23 on 2024-05-06 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0009_alter_sitesettings_domain_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='fill_fee_cold_chain',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='fill_fee_regular',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='margin_cold_chain',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='margin_regular',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='ship_fee_cold_chain',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='ship_fee_regular',
        ),
    ]
