# Generated by Django 3.2.23 on 2024-08-08 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0017_channel_include_draft_order_in_voucher_usage'),
        ('pharmacy', '0010_auto_20240506_1941'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='channels',
            field=models.ManyToManyField(to='channel.Channel'),
        ),
    ]
