version: '3.7'
services:
    app:
        build:
          context: .
          dockerfile: Dockerfile4dev
        image: pharmacy
        restart: always
        volumes:
        - ./:/app
        network_mode: host
