# Generated by Django 3.2.18 on 2023-03-29 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0077_merge_20230310_1107"),
        ("app", "0021_app_author"),
    ]

    operations = [
        migrations.CreateModel(
            name="AppEvent",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("installed", "installed"),
                            ("activated", "activated"),
                            ("deactivated", "deactivated"),
                        ],
                        max_length=255,
                    ),
                ),
                (
                    "app",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="app.app",
                    ),
                ),
                (
                    "requestor_app",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="app.app",
                    ),
                ),
                (
                    "requestor_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="account.user",
                    ),
                ),
            ],
            options={
                "ordering": ("date",),
            },
        ),
    ]
