# Generated by Django 3.2.18 on 2023-03-30 06:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0022_appevent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appevent",
            name="type",
            field=models.CharField(
                choices=[
                    ("installed", "installed"),
                    ("activated", "activated"),
                    ("deactivated", "deactivated"),
                ],
                db_index=True,
                max_length=255,
            ),
        ),
    ]
