# Generated by Django 3.2.18 on 2023-03-30 06:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0023_alter_appevent_type"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="appevent",
            options={"ordering": ("created_at",)},
        ),
        migrations.RenameField(
            model_name="appevent",
            old_name="date",
            new_name="created_at",
        ),
    ]
